name: Build and Push Docker Image

on:
  push:
    branches: ["main"] # or whichever branch you deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Create .env file from GitHub Secret (like GitLab file variable)
      - name: Create .env file
        shell: bash
        run: |
          echo "${{ secrets.ENV_FILE }}" | tr '\r' '\n' > .env
          echo "✅ .env file created successfully"
          ls -l .env

      # 3️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.IMAGE_NAME }}:${{ github.sha }}
